baseURL = 'https://pages.micahrl.com/GridCraft'
languageCode = 'en-us'
title = 'GridCraft Documentation'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/mrled/GridCraft"
  weight = 10

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true

  # (Optional, default docs) Specify root page to render child pages as menu.
  BookSection = 'docs'

  # Set source repository location.
  BookRepo = 'https://github.com/mrled/GridCraft'

  # Enable "Edit this page" links for 'doc' page type.
  BookEditPath = 'edit/master'

  # Configure the date format used on the pages
  BookDateFormat = 'January 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  BookComments = false
