name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build GridCraft
      run: make dist/GridCraft.spoon.zip

    - name: Upload release artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/GridCraft.spoon.zip
        asset_name: GridCraft.spoon.zip
        asset_content_type: application/zip

    - name: Upload temporary artifact
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: actions/upload-artifact@v4
      with:
        name: GridCraft-${{ github.sha }}
        path: ./dist/GridCraft.spoon.zip
        retention-days: 30