name: Build and Release

on:
  push:
    # Run on any tag that starts with 'v'
    tags: [ 'v*' ]
  # Run on any pull request to any branch
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Deep clone repo, including tags

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build GridCraft
      id: build
      run: |+
        make dist/GridCraft.spoon.zip
        echo "version=$(cat dist/GridCraft.spoon/version.txt)" >> $GITHUB_OUTPUT

    - name: Create Release
      if: startsWith(steps.build.outputs.version, 'v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.build.outputs.version }}
        COMMIT: ${{ github.sha }}
      run: >
        gh release create "$VERSION" --title "$VERSION" --generate-notes --target "$COMMIT" dist/GridCraft.spoon.zip

    - name: Upload temporary artifact
      if: "!startsWith(steps.build.outputs.version, 'v')"
      uses: actions/upload-artifact@v4
      with:
        name: GridCraft-${{ github.sha }}
        path: ./dist/GridCraft.spoon.zip
        retention-days: 30