name: Build and Release GridCraft Spoon

on:
  release:
    types: [published]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for proper git describe

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Determine version and artifact name
      id: version
      run: |
        # Get version from git tags
        if git describe --tags --exact-match HEAD >/dev/null 2>&1; then
          # On a tagged commit (release)
          VERSION=$(git describe --tags --exact-match HEAD)
          ASSET_NAME="GridCraft.spoon.zip"
        else
          # On a branch/PR
          # Try to get the latest tag, fallback if no tags exist
          if LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null); then
            VERSION="${LATEST_TAG}-devel"
          else
            VERSION="0.1.0-devel"
          fi
          
          SHORT_HASH=$(git rev-parse --short HEAD)
          ASSET_NAME="GridCraft.spoon-${SHORT_HASH}.zip"
        fi
        
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "ASSET_NAME=${ASSET_NAME}" >> $GITHUB_OUTPUT
        echo "Building version: ${VERSION}"
        echo "Asset name: ${ASSET_NAME}"

    - name: Build GridCraft Spoon
      run: |
        make VERSION="${{ steps.version.outputs.VERSION }}" dist/GridCraft.spoon.zip

    - name: Upload Release Asset (for releases)
      if: github.event_name == 'release'
      run: |
        gh release upload ${{ github.event.release.tag_name }} ./dist/GridCraft.spoon.zip --name "${{ steps.version.outputs.ASSET_NAME }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload PR Artifact (for pull requests)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.version.outputs.ASSET_NAME }}
        path: ./dist/GridCraft.spoon.zip
        retention-days: 30